### ISSUE TITLE
Error of PyTorch vs. CUDA version

### ISSUE THREAD

**Issue by peterhsshin** [salesforce/ETSformer#1]
I'm getting the following error.

```
Traceback (most recent call last):
  File "run.py", line 117, in <module>
    exp.train(setting)
  File "/nvme/git/ETSformer/exp/exp_main.py", line 140, in train
    dec_inp = torch.zeros_like(batch_y[:, -self.args.pred_len:, :]).float()
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.


```
I believe this error is caused by the CUDA version being 11.7 (the newest), and is incompatible with the older torch version (1.11.0 specified in the requirements.txt).

I tried upgrading the torch version but found errors.  Would you please update the torch code to the latest?  I know that it breaks the transformer code as mentioned here:
https://github.com/pytorch/pytorch/issues/80569

**Comment by peterhsshin** [comment]
I'll downgrade CUDA after reading this:
https://discuss.pytorch.org/t/latest-cuda-toolkit-release-11-7-is-it-compatible-with-pytorch/152824/5

**Comment by peterhsshin** [comment]
I'll downgrade CUDA after reading this:
https://discuss.pytorch.org/t/latest-cuda-toolkit-release-11-7-is-it-compatible-with-pytorch/152824/5
